- hosts: web
  tasks:
       - name: Configuring yum for docker
         yum_repository:
               name: docker
               #name of the repository and id for the repo
               baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
               gpgcheck: no
               description: try
               #name of this configuration
               state: present
               #repo to be created
         register: history
       - name: installing docker 
         package: 
               name: docker-ce-18.09.1-3.el7.x86_64
               state: present      
         when: history.failed == false
         register: yum
       - name: starting docker service
         service: 
               name: "docker"
               state: started
         register: status
         when: yum.failed == false
       - name: Signing in docker images from docker hub
         command: docker login -u username -p password
         register: login
         when: status.failed == false
       - name: pulling docker images of httpd
         command: docker pull httpd
         register: pull
         when: login.failed == false
       - name: transfering file to target system
         copy:
              src: /var/www/html/ansible.html
              dest: /var/www/html/ansible.html
       - name: launching container 
         command: docker run -dit -p 81:80 -v /var/www/html/:/usr/local/apache2/htdocs  httpd
         register: launch
         when: pull.failed == false
       - name: installing httpd
         package: 
              name: httpd
              state: present
         register: http
       - name: starting httpd on BaseOS
         service:
              name: httpd
              state: started
         when: http.failed == false   

       - debug:
              msg: yum.stdout
              msg: pull.stdout         
